export const englishTopics = [
  "Books",
  "Coins",
  "Stamps",
  "Postcards",
  "Comics",
  "Action Figures",
  "Trading Cards",
  "Vinyl Records",
  "Movie Memorabilia",
  "Sports Jerseys",
  "Autographs",
  "Art Prints",
  "Antique Furniture",
  "Vintage Clothing",
  "Toy Cars",
  "Dolls",
  "Model Trains",
  "Musical Instruments",
  "Movie Props",
  "Fine China",
  "Wristwatches",
  "Jewelry",
  "Comic Books",
  "Bottles",
  "Sports Memorabilia",
  "Board Games",
  "Vintage Cameras",
  "Sneakers",
  "Figurines",
  "Vinyl Toys",
  "Vintage Posters",
  "Concert Tickets",
  "Vintage Magazines",
  "Musical Records",
  "Action Cameras",
  "Snow Globes",
  "Candles",
  "Shot Glasses",
  "Beer Steins",
  "Vintage Maps",
  "Pocket Knives",
  "Keychains",
  "Trading Pins",
  "Artifacts",
  "Antique Clocks",
  "Hats",
  "Lighters",
  "Fountain Pens",
  "Vintage Telephones",
  "Vinyl Music Albums",
  "Other",
];

export const georgianTopics = [
  "წიგნები",
  "მონეტები",
  "შტამპები",
  "ღია ბარათები",
  "კომიქსები",
  "სამოქმედო ფიგურები",
  "სავაჭრო ბარათები",
  "ვინილის ჩანაწერები",
  "კინო მოგონებები",
  "სპორტული მაისურები",
  "ავტოგრაფები",
  "ხელოვნების ანაბეჭდები",
  "ანტიკური ავეჯი",
  "ვინტაჟური ტანსაცმელი",
  "Სათამაშო მანქანები",
  "თოჯინები",
  "მატარებლების მოდელები",
  "მუსიკალური ინსტრუმენტები",
  "კინო რეკვიზიტები",
  "ძვირფასი ჭურჭელი",
  "მაჯის საათები",
  "სამკაულები",
  "Კომიქსები",
  "ბოთლები",
  "სპორტული მოგონებები",
  "Სამაგიდო თამაშები",
  "ვინტაჟური კამერები",
  "სპორტულები",
  "ფიგურები",
  "ვინილის სათამაშოები",
  "ვინტაჟური პლაკატები",
  "Კონცერტის ბილეთები",
  "ვინტაჟური ჟურნალები",
  "მუსიკალური ჩანაწერები",
  "სამოქმედო კამერები",
  "თოვლის გლობუსები",
  "სანთლები",
  "ალკოჰოლის ჭიქები",
  "ლუდის სტეინსი",
  "რთველის რუკები",
  "ჯიბის დანები",
  "გასაღებები",
  "ქინძისთავები",
  "არტეფაქტები",
  "ანტიკური საათები",
  "ქუდები",
  "ასანთები",
  "ძველებური კალმები",
  "ვინტაჟური ტელეფონები",
  "ვინილის მუსიკალური ალბომები",
  "სხვა",
];
